Chart.yaml, README.md, templates/ingress.yaml, templates/redis-service.yaml, templates/redis-tmp-deploy.yaml, values.yaml
Features of this change :
* hostname is only set once
* redis deployment and service are now optional
* less duplication of environment variables (using anchors)
=> Make the chart more DRY

Chart.yaml, README.md, templates/api-deployment.yaml, templates/clock-deployment.yaml, templates/events-worker-deployment.yaml, templates/worker-deployment.yaml, values.yaml
- Add `logLevel` for each back end service
- Bump version
=> feat(logs): Add log level configuration

Chart.yaml, README.md, templates/secrets.yaml
- Keep secrets even if we uninstall Lago
=> fix(secrets): Fix keep secrets

Chart.yaml, README.md, templates/secrets.yaml, values.yaml
=> fix(secrets): use fixed secret name

.github/workflows/chart-testing.yml, examples/ci/values.yml
=> misc(CI): Add CI

templates/api-deployment.yaml, templates/events-worker-deployment.yaml, templates/worker-deployment.yaml, values.yaml
- Add a basic liveness for sensitives services `api`, `worker` and `events-worker` 
We should add better liveness check : Database and Redis check
=> feat(liveness): Add basic liveness

Chart.yaml, README.md, templates/api-deployment.yaml, templates/events-worker-deployment.yaml, templates/worker-deployment.yaml, values.yaml
- Fix migrations and kubectlVersion
- bump to 1.0.0
=> misc(version): bump to 1.0.0

templates/network-policy.yaml, values.yaml
Add a configurable global network policy, empty and disabled by default.
=> feat: add a network policy

templates/api-deployment.yaml, templates/clock-deployment.yaml, templates/events-worker-deployment.yaml, templates/front-deployment.yaml, templates/migrate-job.yaml, templates/pdf-deployment.yaml, templates/worker-deployment.yaml, values.yaml
More reasonable memory requests values are also configured.
=> feat: allow configuration of resource limits

Chart.yaml, README.md, values.yaml
https://github.com/getlago/lago-helm-charts/issues/40
=> misc(version): bump to v1.2.1

.github/workflows/release.yml
Fixing chart repostiry action this should fix issues #82 and #83
=> feat(charts): Fixing chart repository pipeline

templates/worker-deployment.yaml
This should fix issue https://github.com/getlago/lago-helm-charts/issues/87
=> fix(worker-deploy) fixing worker deploy with minio

templates/events-worker-deployment.yaml, templates/worker-deployment.yaml, values.yaml
make the livenessProbe for worker and events-worker configurable in chart.
=> make liveness probe configurable in chart

.github/workflows/creating_pr.yml
This should fix the action that doesn't create the PR yet ...
=> Fix action 3

.github/workflows/release.yml
This should avoid the "skip" part inside github action
=> fix(action-pr): fixing release bot stuff

.github/workflows/release.yml
This should finally fix the action and auto deploy the Github page stuff
=> fix(github-page): fixing last step of github page

.github/workflows/creating_pr.yml, .github/workflows/release.yml
- Renaming workflow prep release
- fixing deploy tar without github action
=> fix(github-page): fixing both github action to release

README.md, templates/api-deployment.yaml, templates/clock-deployment.yaml, templates/events-worker-deployment.yaml, templates/front-deployment.yaml, templates/pdf-deployment.yaml, templates/worker-deployment.yaml, values.yaml
=> Enhance Helm Chart Flexibility: Support for Tolerations and Improved Scheduling Defaults

Chart.yaml, templates/api-deployment.yaml, templates/clock-deployment.yaml, templates/webhook-worker-deployment.yaml, templates/worker-deployment.yaml, values.yaml
- Add a dedicated webhook worker
- Bump to `1.17.4`
=> feat(worker): Add webhook worker

.zed/settings.json, templates/api-deployment.yaml, templates/billing-worker-deployment.yaml, templates/clock-deployment.yaml, templates/clock-worker-deployment.yaml, templates/events-worker-deployment.yaml, templates/front-deployment.yaml, templates/pdf-deployment.yaml, templates/webhook-worker-deployment.yaml, templates/worker-deployment.yaml
Using strategy: Recreate is not ideal as it means downtime.
=> feat(ZeroDowntime) -  zero downtime deployments

charts/lago/Chart.yaml, charts/lago/templates/api-hpa.yml, charts/lago/templates/billing-worker-hpa.yaml, charts/lago/templates/clock-worker-hpa.yaml, charts/lago/templates/pdf-hpa.yaml, charts/lago/templates/pdf-worker-hpa.yaml, charts/lago/templates/webhook-worker-hpa.yml, charts/lago/templates/worker-hpa.yaml, charts/lago/values.yaml
- Add a basic HPA configuration
=> feat(hpa): Add HPA support for BE services

charts/lago/templates/_helpers.tpl
Fixes #151
Replace any non-numeric char in minor version
=> Replace any non-numeric char in minor version

README.md, charts/lago/Chart.yaml, charts/lago/templates/secrets.yaml, charts/lago/values.yaml
- Permit usage of `encryptionprimaryKey`, `encryptionDeterministicKey` and `encryptionKeyDerivationSalt` with `existingSecret`
- Add some docs around `existingSecret`
=> fix(secrets): Add encryptions keys under existingSecrets

charts/lago/Chart.yaml, charts/lago/ci/basic-values.yaml, charts/lago/ci/dedicated-workers-values.yaml, charts/lago/templates/api-deployment.yaml, charts/lago/templates/billing-worker-deployment.yaml, charts/lago/templates/clock-deployment.yaml, charts/lago/templates/events-worker-deployment.yaml, charts/lago/templates/payment-worker-deployment.yaml, charts/lago/templates/payment-worker-hpa.yaml, charts/lago/templates/pdf-worker-deployment.yaml, charts/lago/templates/webhook-worker-deployment.yaml, charts/lago/templates/worker-deployment.yaml, charts/lago/values.yaml
- Add a dedicated payment worker
=> feat(payments): Add dedicated payments worker

README.md, charts/lago/Chart.yaml, charts/lago/templates/api-deployment.yaml, charts/lago/templates/billing-worker-deployment.yaml, charts/lago/templates/clock-worker-deployment.yaml, charts/lago/templates/events-worker-deployment.yaml, charts/lago/templates/payment-worker-deployment.yaml, charts/lago/templates/pdf-deployment.yaml, charts/lago/templates/pdf-worker-deployment.yaml, charts/lago/templates/webhook-worker-deployment.yaml, charts/lago/templates/worker-deployment.yaml, charts/lago/values.yaml
- https://github.com/getlago/lago-helm-charts/issues/149
- add livenessProbe on http 8080 for all workers
=> add new http livenessProbe for workers

README.md, Taskfile.yaml
Update README to include development setup and prerequisites. Update README with examples
=> feat(task): Add taskfile for common workflows
