getlago/lago-helm-charts

Chart.yaml
values.yaml

misc(version): Bump to 0.23.0-beta

---

templates/api-deployment.yaml
templates/secrets.yaml
templates/worker-deployment.yaml

fix smtp nil error when smtp enabled equals true. tested in the K3S locally but you can verify it once more.

fix smtp nil error when smtp is enabled

---

Chart.yaml
README.md
templates/api-deployment.yaml
templates/clock-deployment.yaml
templates/events-worker-deployment.yaml
templates/front-deployment.yaml
templates/pdf-deployment.yaml
templates/worker-deployment.yaml
values.yaml

- Support custom annotations on deployments
- Support `serviceAccountName` to permit usage of AWS IRSA, note : you should create your service account before

misc(pods): Add annotations and Service accounts on pods

---

templates/api-deployment.yaml
templates/worker-deployment.yaml
values.yaml

Fixes the use of `global.s3.aws.accessKeyId` and properly assign it to the API & Worker's env vars.
Also added the `endpoint` support for S3 compatible services like MinIO.

fix(s3): Fix S3 secret env var population. Added S3 endpoint support

---

templates/migrate-job.yaml

To fix Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)

Redis secret is missing.

---

Chart.yaml

- The `Charts.yaml` file has he v2 syntax (presence of a `dependencies` key, [source](https://helm.sh/docs/topics/charts/#the-apiversion-field)) but is declared as v1. Patch it into **v2**.
- This fixes charts installs with helm v3
- This will force the chart to be only available with helm v3

Update chart apiVersion

---

Chart.yaml
templates/_helpers.tpl
templates/api-deployment.yaml
templates/events-worker-deployment.yaml
templates/migrate-job.yaml
templates/serviceaccount.yml
templates/worker-deployment.yaml
values.yaml

- Modified jobs so they have a controlled random string (generated from the hash of the values.yaml concatenated with the Chart Version) within their name
- Kubernetes jobs are immutable, so if the job still exists and helm tries to apply a new job on top of it, helm will raise an error saying that the Job resource is immutable. Adding some suffix to its name will allow to create a new job on a new version of the release. 
- Using `kubectl watch` to verify that migrations have run is probably a bad idea: Users could, for instance, decide to run migrations another mechanism and not the batch API. Plus, that prevents the job from being cleaned up (or else deployments won't run) and will accumulate on the namespace. Instead, checking migration version should probably be done directly in the …

Add by default a `ttlSecondsAfterFinished`

---

.github/workflows/release.yml

This Pull Request introduces an update to the GitHub Actions workflow to align with the current chart structure.
- Added path configurations in the CI workflow to ensure correct paths for both the main chart.
- Updated Helm dependencies using `helm dependency update` to ensure all charts are up to date.
- Maintained the automation for chart releases and publishing to GitHub Pages.
This update is required due to the specific chart structure of the repository. The previous configuration didn't account for the custom path locations of the charts, which could lead to issues during the CI/CD process. By adjusting the paths, we ensure that all charts are correctly linted, packaged, and published.

feat(ci): add paths configuration to GitHub Actions for charts structure

---

templates/migrate-job.yaml

This PR addresses the issue where the Redis client fails to connect with the following error:
```sh
RedisClient::CannotConnectError: Operation already in progress - connect(2) for 10.99.105.81:6379 (RedisClient::CannotConnectError)
```
The fix involves adjusting the initContainers logic in the Job migration YAML to ensure that the application waits for Redis to be fully ready before attempting a connection. This should prevent the connection errors due to Redis not being available in time.
- Added initContainers to wait for Redis to be ready.
- Adjusted timeouts for better reliability during migration tasks.
This should fix the Redis connection issue without introducing breaking changes.

Fix: corrected initContainers indentation and conditionals in Job migration YAML

---

README.md
templates/storage-data-persistentvolumeclaim.yaml
values.yaml

This pull request improves the documentation for both the API and frontend configurations by adding missing parameters and clarifying default behaviors. The following changes have been made:
- **API Configuration**: Added documentation for missing parameters such as `logStdout`, `logLevel`, `sidekiqWeb.enabled`, `volumes.accessModes`, `volumes.storage`, `podAnnotations`, and `podLabels`.
- **Frontend Configuration**: Included documentation for `podAnnotations` and `podLabels` parameters.
- **Persistent Volume Claim (PVC) Handling**: Clarified that the default behavior is to fallback to a PVC if neither S3 nor MinIO is configured, although this is strongly discouraged.
This PR aims to provide clearer guidance on configuration options and their defaults, improving overall usability and …

Enhance API and Frontend Configuration Documentation and Default PVC Handling

---

templates/api-deployment.yaml
templates/clock-deployment.yaml
templates/events-worker-deployment.yaml
templates/front-deployment.yaml
templates/pdf-deployment.yaml
templates/storage-data-persistentvolumeclaim.yaml
templates/worker-deployment.yaml
values.yaml

This PR introduces the following changes:
1. **feat(helm): Support for `extraEnv` variables**  
Added support for dynamic environment variables via the `extraEnv` section in the `values.yaml` for the following deployments:
- `api`
- `front`
- `worker`
- `events-worker`
- `clock`
- `pdf`
2. **fix(pvc): Resolved conditional issue in PVC template**  
Fixed the logic error in the PersistentVolumeClaim template where multiple `not` conditions were incorrectly applied, causing template rendering issues. Now the PVC is correctly created when both `s3.enabled` and `minio.enabled` are set to `false`.
These changes allow users to configure additional environment variables without directly modifying the deployment templates, providing greater flexibility. For example, it was previously impossible to …

feat(helm): add support for extraEnv variables in api, front, worker, events-worker, clock, and pdf deployments for dynamic environment configuration

---

.github/workflows/release.yml

feat(actions): Automatic bump the version when doing a release

---

.github/workflows/creating_pr.yml
.github/workflows/release.yml

This Pull Request separates the release workflow into two distinct workflows to comply with SOC 2 requirements : we can't directly commit on main even if its a bot.
- Workflow 1: Creates a release Pull Request to update version numbers.
- Workflow 2: Publishes the Helm charts upon merging the release PR into the main branch.
This ensures that all code changes are reviewed and approved before being merged, aligning with our compliance standards.

chore(workflows): split release workflow into two for SOC 2 compliance

---

.github/workflows/creating_pr.yml

All in the title to prevent error like :
```
/usr/bin/git symbolic-ref HEAD --short
release/1.14.0
Working base is branch 'release/1.14.0'
Error: The 'base' and 'branch' for a pull request must be different branches. Unable to continue.
```

fix(action-pr): fixing creating of pull request

---

templates/worker-deployment.yaml

This PR adds the missing S3 environment variables to the worker-deployment.yaml file when using MinIO. It ensures that the worker deployment can interact with the S3-compatible storage just like the API deployment, addressing the issue where S3 credentials were not included in the worker configuration. Releated to #87

fix(worker-deployment): include S3 credentials when using MinIO

---

templates/webhook-worker-deployment.yaml

We sometimes call `file_url` from Invoice in web hooks, this requires this env var to be set.

bug(WebhookWorker) - make sure LAGO_API_URL is set in webhook-worker

---

README.md
charts/lago/Chart.yaml
charts/lago/templates/_helpers.tpl
charts/lago/templates/api-deployment.yaml
charts/lago/templates/billing-worker-deployment.yaml
charts/lago/templates/clock-deployment.yaml
charts/lago/templates/clock-worker-deployment.yaml
charts/lago/templates/events-worker-deployment.yaml
charts/lago/templates/pdf-worker-deployment.yaml
charts/lago/templates/secrets.yaml
charts/lago/templates/webhook-worker-deployment.yaml
charts/lago/templates/worker-deployment.yaml
charts/lago/values.yaml

This PR resolves the issue [Wrong encryption keys used when setting global.existingSecret](https://github.com/getlago/lago-helm-charts/issues/163), introduced by the commit [fix(secrets): Add encryption keys under existingSecrets](https://github.com/getlago/lago-helm-charts/commit/d1ace4fd7373d02c1740e2e4ed5a169ce1a7e53f). It ensures that encryption keys are correctly sourced from the provided existing secret.
Additionally, the previous commit introduced a breaking change for users already utilizing an existing secret, as it inadvertently caused the loss of encryption keys stored in `{{ .Release.Name }}-secrets` upon chart updates. To address this, the PR introduces distinct fields for `existingSecret`: one for global purposes and another specifically for encryption purposes, thus …

fix: fix encryption secret

---

charts/lago/Chart.yaml
charts/lago/templates/api-deployment.yaml
charts/lago/templates/billing-worker-deployment.yaml
charts/lago/templates/clock-worker-deployment.yaml
charts/lago/templates/front-deployment.yaml
charts/lago/templates/pdf-worker-deployment.yaml
charts/lago/templates/worker-deployment.yaml
charts/lago/values.yaml

Some clients don't need pdfs of invoices, credit notes and payment receipts.
This PR adds an ENV var to disable generating pdfs: `LAGO_DISABLE_PDF_GENERATION`

feat(pdf): Add env var to disable generating pdfs

---

charts/lago/Chart.yaml
charts/lago/templates/api-deployment.yaml
charts/lago/templates/billing-worker-deployment.yaml
charts/lago/templates/clock-deployment.yaml
charts/lago/templates/clock-worker-deployment.yaml
charts/lago/templates/events-worker-deployment.yaml
charts/lago/templates/migrate-job.yaml
charts/lago/templates/payment-worker-deployment.yaml
charts/lago/templates/pdf-worker-deployment.yaml
charts/lago/templates/secrets.yaml
charts/lago/templates/serviceaccount.yml
charts/lago/templates/webhook-worker-deployment.yaml
charts/lago/templates/worker-deployment.yaml

Eliminate the 'wait-for-migrations' initContainers from various worker and deployment templates since we are now relying on the hook.

refactor: use helm hooks to handle migration

---

.github/workflows/chart-testing.yml
Taskfile.yaml
charts/lago/Chart.yaml
charts/lago/ci/postgres.yml
charts/lago/ci/redis.yml

Eliminate the 'lago' namespace specification from the Postgres and Redis chart files, as well as from the Taskfile and GitHub Actions workflow. This change simplifies multiple parts of the github action and testing workflow

refactor: Remove 'lago' namespace from Helm chart configurations
